<?php
/*
Plugin Name: Widget Post
Plugin URI: https://eni-ecole.fr/
Description: Widget qui sert d'exemple pour le cours WordPress et qui permet de lister des articles
suivant une catégorie.
Version: 0.1
Requires at least: 6.8
Requires PHP: 8.2
Author: ENI ECOLE
Author URI: https://eni-ecole.fr/
License: GPLv2 or later
Copyright 2025 RD2WM_020 (email:{dsanchez@campus-eni.fr})
Text Domain: eni
*/
class Widget_Post extends WP_Widget {
    /**
    Méthode de construction du même nom que la classe qui sert à configurer le widget.
     */
    function Widget_Post(){
        $widget_ops = array('classname'=>'widget-post',
            'description'=>'Widget permmettant l\'affichage d\'une liste d\'articles selon la catégorie');
        $control_ops = array('width'=>300,
            'height'=>350,
            'id_base'=>'widget-post');
        $this->WP_Widget('widget-post','Widget Post', $widget_ops, $control_ops);
    }

    /**
    Méthode qui sert à afficher le widget côté internaute.
     */
    function widget($args, $instance)
    {
        //parent::widget($args, $instance); // TODO: Change the autogenerated stub
    }

    /**
    Méthode qui sert à mettre à jour les options du widget
     */
    function update($new_instance, $old_instance)
    {
        //return parent::update($new_instance, $old_instance); // TODO: Change the autogenerated stub
    }

    /**
    Méthode qui sert à afficher les formulaires de configuration du widget dans l'administration.
     */
    function form($instance){
        $defaults=array('title'=>'Articles');
        $instance=wp_parse_args($instance, $defaults);
        ?>
        <p>
            <label for="<?php echo $this->get_field_id('title');?>">Titre:</label>
            <input type="text" name="<?php echo $this->get_field_name('title');?>"
                   id="<?php echo $this->get_field_id('title');?>"
                   value="<?php echo $instance['title'];?>"
                   placeholder="Titre"
                   style="width:100%;"
            />
        </p>
        <p>
            <label for="<?php echo $this->get_field_id('category');?>">Catégorie :</label>
            <select name="<?php echo $this->get_field_name('category');?>"
                    id="<?php echo $this->get_field_id('category');?>">
                <option>Toutes les catégories</option>
                <?php
                    foreach ((get_categories()) as $cat) {
                        if($instance['category'] == $cat->cat_ID){
                            $selected='selected="selected';
                        }else{
                            $selected='';
                        }
                        echo '<option '.$selected.' value="'.$cat->cat_ID.'">'.$cat->cat_name.'</option>';
                    }

                ?>
            </select>
        </p>
        <?php
    }

    function register_my_widget(){
        register_widget('Widget_Post');
    }
}

add_action('widget_init','register_my_widget');

